export default ROLES = [
  {label: 'PM', value: 1},
  {label: 'SEM', value: 2},
  {label: 'SOM', value: 3},
  {label: 'LOGISTIK', value: 4},
  {label: 'PENBAR', value: 5},
  {label: 'GSP', value: 6},
  {label: 'SP', value: 7},
  {label: 'ARK', value: 8},
  {label: 'HSM', value: 9},
  {label: 'HSE-O', value: 10},
  {label: 'QCM', value: 11},
  {label: 'QC-O', value: 12},
  {label: 'SE', value: 13},
  {label: 'ME', value: 14},
];
