export default ROLES = [
  { label: "PM", value: 1 },
  { label: "SEM", value: 2 },
  { label: "POP", value: 3 },
  { label: "LOGISTIK", value: 4 },
  { label: "PENBAR", value: 5 },
  { label: "SOM", value: 6 },
  { label: "GSP", value: 7 },
  { label: "SP", value: 8 },
  { label: "ARK", value: 9 },
  { label: "QCO", value: 10 },
  { label: "HSEO", value: 11 },
  { label: "SAK", value: 12 },
  { label: "SE", value: 13 },
  { label: "ADMIN", value: 14 },
];
